name: clearsale
description: Package para conectar uma aplicação Dart com a Clearsale
version: 1.0.0-dev.9
author: F-Team <david@flutterando.com.br>
homepage: http://f-team.dev/
repository: https://github.com/davidsdearaujo/clearsale.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  collection: ^1.14.13
  meta: ^1.2.3
  dartz: ^0.9.1
  http: ^0.12.2

dev_dependencies:
  mockito: ^4.1.1
  test: ^1.15.4
